### ISSUE TITLE
Adaptation for other meters

### ISSUE THREAD

**Issue by Wronek** [astraliens/home-assistant-gama-300-dlms-meter#1]
Hi, 
Is it possible to adapt to other meters?
I have Pafal meter and I connect with him using Gurux GXDLMSDirector and parameters from below image. The difference from your counter in mine is the type of address. Where I can change this?

![image](https://github.com/astraliens/home-assistant-gama-300-dlms-meter/assets/47157940/3f7ee107-bf92-4aef-85a4-2d22bccada18)

**Comment by astraliens** [comment]
addresses and sensor names are listed in dlms_read_data/meter_data.json and dlms_read_data/meter_param.json
dlms configuration can be adjusted in dlms_read_data/MeterClient.py
